import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { getCurrentUser } from '@/lib/auth';

const EXTRA_INGREDIENTS = [
  // Viandes — variantes manquantes
  { name: 'Steak haché', category: 'Viandes', emoji: '🥩' },
  { name: 'Filet de bœuf', category: 'Viandes', emoji: '🥩' },
  { name: 'Entrecôte', category: 'Viandes', emoji: '🥩' },
  { name: 'Faux-filet', category: 'Viandes', emoji: '🥩' },
  { name: 'Côte de bœuf', category: 'Viandes', emoji: '🥩' },
  { name: 'Bavette', category: 'Viandes', emoji: '🥩' },
  { name: 'Onglet', category: 'Viandes', emoji: '🥩' },
  { name: 'Tranche de bœuf', category: 'Viandes', emoji: '🥩' },
  { name: 'Bœuf bourguignon', category: 'Viandes', emoji: '🥩' },
  { name: 'Paleron', category: 'Viandes', emoji: '🥩' },
  { name: 'Joue de bœuf', category: 'Viandes', emoji: '🥩' },
  { name: 'Jarret de bœuf', category: 'Viandes', emoji: '🥩' },
  { name: 'Viande hachée', category: 'Viandes', emoji: '🥩' },
  { name: 'Steak haché de dinde', category: 'Viandes', emoji: '🍗' },
  { name: 'Steak haché de poulet', category: 'Viandes', emoji: '🍗' },
  { name: 'Escalope de poulet', category: 'Viandes', emoji: '🍗' },
  { name: 'Cuisse de poulet', category: 'Viandes', emoji: '🍗' },
  { name: 'Aile de poulet', category: 'Viandes', emoji: '🍗' },
  { name: 'Blanc de poulet', category: 'Viandes', emoji: '🍗' },
  { name: 'Filet de poulet', category: 'Viandes', emoji: '🍗' },
  { name: 'Escalope de dinde', category: 'Viandes', emoji: '🍗' },
  { name: 'Cuisse de dinde', category: 'Viandes', emoji: '🍗' },
  { name: 'Côtelette de porc', category: 'Viandes', emoji: '🍖' },
  { name: 'Filet mignon', category: 'Viandes', emoji: '🍖' },
  { name: 'Échine de porc', category: 'Viandes', emoji: '🍖' },
  { name: 'Rôti de porc', category: 'Viandes', emoji: '🍖' },
  { name: 'Travers de porc', category: 'Viandes', emoji: '🍖' },
  { name: 'Poitrine de porc', category: 'Viandes', emoji: '🥓' },
  { name: 'Jambon cru', category: 'Viandes', emoji: '🍖' },
  { name: 'Chorizo', category: 'Viandes', emoji: '🌭' },
  { name: 'Coppa', category: 'Viandes', emoji: '🍖' },
  { name: 'Pancetta', category: 'Viandes', emoji: '🥓' },
  { name: 'Bacon', category: 'Viandes', emoji: '🥓' },
  { name: 'Gigot d\'agneau', category: 'Viandes', emoji: '🍖' },
  { name: 'Côtelette d\'agneau', category: 'Viandes', emoji: '🍖' },
  { name: 'Épaule d\'agneau', category: 'Viandes', emoji: '🍖' },
  { name: 'Souris d\'agneau', category: 'Viandes', emoji: '🍖' },
  { name: 'Magret de canard', category: 'Viandes', emoji: '🦆' },
  { name: 'Confit de canard', category: 'Viandes', emoji: '🦆' },
  { name: 'Lapin', category: 'Viandes', emoji: '🐰' },
  { name: 'Veau', category: 'Viandes', emoji: '🥩' },
  { name: 'Escalope de veau', category: 'Viandes', emoji: '🥩' },
  { name: 'Blanquette de veau', category: 'Viandes', emoji: '🥩' },
  { name: 'Osso buco', category: 'Viandes', emoji: '🥩' },

  // Poissons — variantes manquantes
  { name: 'Filet de saumon', category: 'Poissons', emoji: '🐟' },
  { name: 'Pavé de saumon', category: 'Poissons', emoji: '🐟' },
  { name: 'Truite', category: 'Poissons', emoji: '🐟' },
  { name: 'Filet de cabillaud', category: 'Poissons', emoji: '🐟' },
  { name: 'Filet de merlu', category: 'Poissons', emoji: '🐟' },
  { name: 'Sole', category: 'Poissons', emoji: '🐟' },
  { name: 'Bar', category: 'Poissons', emoji: '🐟' },
  { name: 'Loup de mer', category: 'Poissons', emoji: '🐟' },
  { name: 'Dorade', category: 'Poissons', emoji: '🐟' },
  { name: 'Sardine', category: 'Poissons', emoji: '🐟' },
  { name: 'Maquereau', category: 'Poissons', emoji: '🐟' },
  { name: 'Colin', category: 'Poissons', emoji: '🐟' },
  { name: 'Lieu noir', category: 'Poissons', emoji: '🐟' },
  { name: 'Tilapia', category: 'Poissons', emoji: '🐟' },
  { name: 'Panga', category: 'Poissons', emoji: '🐟' },
  { name: 'Espadon', category: 'Poissons', emoji: '🐟' },
  { name: 'Thon frais', category: 'Poissons', emoji: '🐟' },
  { name: 'Calamar', category: 'Poissons', emoji: '🦑' },
  { name: 'Poulpe', category: 'Poissons', emoji: '🐙' },
  { name: 'Gambas', category: 'Poissons', emoji: '🦐' },
  { name: 'Langoustines', category: 'Poissons', emoji: '🦞' },
  { name: 'Saint-Jacques', category: 'Poissons', emoji: '🐚' },
  { name: 'Palourdes', category: 'Poissons', emoji: '🐚' },
  { name: 'Surimi', category: 'Poissons', emoji: '🦀' },
  { name: 'Anchois', category: 'Poissons', emoji: '🐟' },

  // Charcuterie / traiteur
  { name: 'Mortadelle', category: 'Viandes', emoji: '🍖' },
  { name: 'Rosette', category: 'Viandes', emoji: '🍖' },
  { name: 'Saucisson', category: 'Viandes', emoji: '🍖' },
  { name: 'Andouillette', category: 'Viandes', emoji: '🌭' },
  { name: 'Boudin noir', category: 'Viandes', emoji: '🌭' },
  { name: 'Boudin blanc', category: 'Viandes', emoji: '🌭' },
  { name: 'Foie gras', category: 'Viandes', emoji: '🍽️' },
  { name: 'Rillettes', category: 'Viandes', emoji: '🫙' },

  // Fromages manquants
  { name: 'Comté', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Camembert', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Brie', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Roquefort', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Emmental', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Reblochon', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Saint-Nectaire', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Fourme d\'Ambert', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Fromage à raclette', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Halloumi', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Burrata', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Cheddar', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Gorgonzola', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Pecorino', category: 'Produits laitiers', emoji: '🧀' },
  { name: 'Fromage blanc', category: 'Produits laitiers', emoji: '🫙' },
  { name: 'Petit-suisse', category: 'Produits laitiers', emoji: '🫙' },
  { name: 'Lait concentré', category: 'Produits laitiers', emoji: '🥛' },
  { name: 'Lait de soja', category: 'Produits laitiers', emoji: '🥛' },
  { name: 'Lait d\'amande', category: 'Produits laitiers', emoji: '🥛' },
  { name: 'Lait d\'avoine', category: 'Produits laitiers', emoji: '🥛' },

  // Légumes manquants
  { name: 'Navet', category: 'Légumes', emoji: '🥔' },
  { name: 'Panais', category: 'Légumes', emoji: '🥕' },
  { name: 'Topinambour', category: 'Légumes', emoji: '🥔' },
  { name: 'Potiron', category: 'Légumes', emoji: '🎃' },
  { name: 'Courge butternut', category: 'Légumes', emoji: '🎃' },
  { name: 'Potimarron', category: 'Légumes', emoji: '🎃' },
  { name: 'Endive', category: 'Légumes', emoji: '🥬' },
  { name: 'Roquette', category: 'Légumes', emoji: '🥬' },
  { name: 'Chou rouge', category: 'Légumes', emoji: '🥬' },
  { name: 'Chou frisé', category: 'Légumes', emoji: '🥬' },
  { name: 'Chou de Bruxelles', category: 'Légumes', emoji: '🥬' },
  { name: 'Brocoli-rave', category: 'Légumes', emoji: '🥦' },
  { name: 'Cèleri-rave', category: 'Légumes', emoji: '🥔' },
  { name: 'Échalote', category: 'Légumes', emoji: '🧅' },
  { name: 'Oignon rouge', category: 'Légumes', emoji: '🧅' },
  { name: 'Tomates cerises', category: 'Légumes', emoji: '🍅' },
  { name: 'Poivron rouge', category: 'Légumes', emoji: '🫑' },
  { name: 'Poivron jaune', category: 'Légumes', emoji: '🫑' },
  { name: 'Edamame', category: 'Légumes', emoji: '🫘' },
  { name: 'Blette', category: 'Légumes', emoji: '🥬' },
  { name: 'Cresson', category: 'Légumes', emoji: '🌿' },
  { name: 'Mâche', category: 'Légumes', emoji: '🥬' },
  { name: 'Germes de soja', category: 'Légumes', emoji: '🌱' },
  { name: 'Pousses de bambou', category: 'Légumes', emoji: '🎋' },
  { name: 'Algue nori', category: 'Légumes', emoji: '🟢' },
  { name: 'Shiitake', category: 'Légumes', emoji: '🍄' },

  // Fruits manquants
  { name: 'Cerise', category: 'Fruits', emoji: '🍒' },
  { name: 'Pêche', category: 'Fruits', emoji: '🍑' },
  { name: 'Abricot', category: 'Fruits', emoji: '🍑' },
  { name: 'Melon', category: 'Fruits', emoji: '🍈' },
  { name: 'Pastèque', category: 'Fruits', emoji: '🍉' },
  { name: 'Figue', category: 'Fruits', emoji: '🟣' },
  { name: 'Grenade', category: 'Fruits', emoji: '🔴' },
  { name: 'Kiwi', category: 'Fruits', emoji: '🥝' },
  { name: 'Noix de coco', category: 'Fruits', emoji: '🥥' },
  { name: 'Fruit de la passion', category: 'Fruits', emoji: '🟡' },
  { name: 'Litchi', category: 'Fruits', emoji: '🔴' },
  { name: 'Papaye', category: 'Fruits', emoji: '🟠' },
  { name: 'Myrtille', category: 'Fruits', emoji: '🫐' },
  { name: 'Framboise', category: 'Fruits', emoji: '🫐' },
  { name: 'Cassis', category: 'Fruits', emoji: '🟣' },
  { name: 'Prune', category: 'Fruits', emoji: '🟣' },
  { name: 'Datte', category: 'Fruits', emoji: '🟤' },
  { name: 'Clémentine', category: 'Fruits', emoji: '🍊' },

  // Féculents manquants
  { name: 'Pâtes fraîches', category: 'Féculents', emoji: '🍝' },
  { name: 'Tagliatelles', category: 'Féculents', emoji: '🍝' },
  { name: 'Spaghetti', category: 'Féculents', emoji: '🍝' },
  { name: 'Penne', category: 'Féculents', emoji: '🍝' },
  { name: 'Farfalle', category: 'Féculents', emoji: '🍝' },
  { name: 'Lasagnes', category: 'Féculents', emoji: '🍝' },
  { name: 'Ravioli', category: 'Féculents', emoji: '🥟' },
  { name: 'Couscous', category: 'Féculents', emoji: '🌾' },
  { name: 'Vermicelles de riz', category: 'Féculents', emoji: '🍜' },
  { name: 'Riz pour sushi', category: 'Féculents', emoji: '🍚' },
  { name: 'Feuille de brick', category: 'Féculents', emoji: '🫓' },
  { name: 'Galette de sarrasin', category: 'Féculents', emoji: '🫓' },
  { name: 'Polenta', category: 'Féculents', emoji: '🌾' },
  { name: 'Pommes frites', category: 'Féculents', emoji: '🍟' },
  { name: 'Flocons d\'avoine', category: 'Féculents', emoji: '🌾' },
  { name: 'Pita', category: 'Féculents', emoji: '🫓' },
  { name: 'Naan', category: 'Féculents', emoji: '🫓' },
  { name: 'Haricots blancs', category: 'Féculents', emoji: '🫘' },
  { name: 'Fèves', category: 'Féculents', emoji: '🫘' },

  // Condiments / sauces manquants
  { name: 'Pesto', category: 'Condiments', emoji: '🌿' },
  { name: 'Sauce worcestershire', category: 'Condiments', emoji: '🍶' },
  { name: 'Sauce hoisin', category: 'Condiments', emoji: '🥢' },
  { name: 'Sauce teriyaki', category: 'Condiments', emoji: '🥢' },
  { name: 'Sauce piri-piri', category: 'Condiments', emoji: '🌶️' },
  { name: 'Tabasco', category: 'Condiments', emoji: '🌶️' },
  { name: 'Sriracha', category: 'Condiments', emoji: '🌶️' },
  { name: 'Ras el hanout', category: 'Épices', emoji: '🟤' },
  { name: 'Curcuma', category: 'Épices', emoji: '🟡' },
  { name: 'Sumac', category: 'Épices', emoji: '🟤' },
  { name: 'Za\'atar', category: 'Épices', emoji: '🌿' },
  { name: 'Cardamome', category: 'Épices', emoji: '🟢' },
  { name: 'Muscade', category: 'Épices', emoji: '🟤' },
  { name: 'Safran', category: 'Épices', emoji: '🟡' },
  { name: 'Anis étoilé', category: 'Épices', emoji: '⭐' },
  { name: 'Citronnelle', category: 'Épices', emoji: '🌿' },
  { name: 'Feuille de laurier', category: 'Épices', emoji: '🌿' },
  { name: 'Aneth', category: 'Épices', emoji: '🌿' },
  { name: 'Ciboulette', category: 'Épices', emoji: '🌿' },
  { name: 'Menthe', category: 'Épices', emoji: '🌿' },
  { name: 'Estragon', category: 'Épices', emoji: '🌿' },
  { name: 'Sauce d\'huître', category: 'Condiments', emoji: '🦪' },
  { name: 'Miso', category: 'Condiments', emoji: '🥢' },
  { name: 'Wasabi', category: 'Condiments', emoji: '🟢' },
  { name: 'Huile de sésame', category: 'Condiments', emoji: '🥢' },
  { name: 'Vinaigre de riz', category: 'Condiments', emoji: '🍶' },
  { name: 'Crème de coco', category: 'Condiments', emoji: '🥥' },
  { name: 'Pâte de curry', category: 'Condiments', emoji: '🟡' },

  // Divers manquants
  { name: 'Tofu', category: 'Autres', emoji: '🟫' },
  { name: 'Tempeh', category: 'Autres', emoji: '🟫' },
  { name: 'Seitan', category: 'Autres', emoji: '🟫' },
  { name: 'Sésame', category: 'Autres', emoji: '🟡' },
  { name: 'Graines de tournesol', category: 'Autres', emoji: '🌻' },
  { name: 'Graines de chia', category: 'Autres', emoji: '🟤' },
  { name: 'Graines de lin', category: 'Autres', emoji: '🟤' },
  { name: 'Noisettes', category: 'Autres', emoji: '🌰' },
  { name: 'Pistaches', category: 'Autres', emoji: '🟢' },
  { name: 'Noix de cajou', category: 'Autres', emoji: '🥜' },
  { name: 'Cacahuètes', category: 'Autres', emoji: '🥜' },
  { name: 'Beurre de cacahuète', category: 'Autres', emoji: '🥜' },
  { name: 'Confiture', category: 'Autres', emoji: '🫙' },
  { name: 'Sirop d\'érable', category: 'Autres', emoji: '🍁' },
  { name: 'Gélatine', category: 'Autres', emoji: '🟡' },
  { name: 'Agar-agar', category: 'Autres', emoji: '🟢' },
  { name: 'Maïzena', category: 'Autres', emoji: '🌾' },
  { name: 'Poudre d\'amande', category: 'Autres', emoji: '🥜' },
  { name: 'Sucre vanillé', category: 'Autres', emoji: '🍬' },
  { name: 'Extrait de vanille', category: 'Autres', emoji: '🟤' },
  { name: 'Levure chimique', category: 'Autres', emoji: '🧫' },
  { name: 'Bicarbonate', category: 'Autres', emoji: '🧂' },
  { name: 'Crème de marrons', category: 'Autres', emoji: '🌰' },
  { name: 'Vin rouge', category: 'Autres', emoji: '🍷' },
  { name: 'Porto', category: 'Autres', emoji: '🍷' },
  { name: 'Rhum', category: 'Autres', emoji: '🥃' },
];

/**
 * POST /api/admin/ingredients/seed
 * Ajoute tous les ingrédients manquants en base (skip ceux qui existent déjà).
 * Admin only.
 */
export async function POST() {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: 'Non autorisé' }, { status: 401 });
  const u = await prisma.user.findUnique({ where: { id: user.id }, select: { role: true } });
  if (u?.role !== 'ADMIN') return NextResponse.json({ error: 'Admin only' }, { status: 403 });

  let created = 0;
  let skipped = 0;
  for (const ing of EXTRA_INGREDIENTS) {
    const existing = await prisma.ingredient.findUnique({ where: { name: ing.name } });
    if (existing) { skipped++; continue; }
    await prisma.ingredient.create({ data: ing });
    created++;
  }

  return NextResponse.json({ created, skipped, total: EXTRA_INGREDIENTS.length });
}
